# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcf5cf5bb585e9a2c62b219715ab81ca034131fface2bb6220a17309ce065125820c64d88ea4ac3ff74d60d2ce21e02bde632926fbaa7ec621d9a22cdbca5751

test:
  secret_key_base: 0a2f28855ab5d56abe551be40c2bc01058af2fb8db1d09bc986e85a2d774b51599a1600e9f9173fefc34e6086fcb7c19c638485445206ce497761fe3cd329445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
